### ISSUE TITLE
ReportDescriptor object has no attribute 'parse_input_report' - Example code is not working.

### ISSUE THREAD

**Issue by NickEngmann** [FFY00/python-hid-parser#3]
<img width="838" alt="Screen Shot 2021-03-09 at 1 25 16 PM" src="https://user-images.githubusercontent.com/1075072/110519093-ebaad780-80da-11eb-9ee8-968a6ccfc68d.png">

After installing with python3 and running the sample code I reach the following error:
`AttributeError: 'ReportDescriptor' object has no attribute 'parse_input_report'`

**Comment by NickEngmann** [comment]
The solution was to install directly from this repo, not `pip3 install hid_parser`

**Comment by FFY00** [comment]
Yes, sorry! This hasn't been released yet :sweat_smile:
